# Workfow to compile the handout 

name: tutorials-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: Tutorials
      
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: /github/workspace/Handout
          root_file: handout.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
        
      - uses: actions/upload-artifact@v2
        with:
          name: Handout
          path: handout.pdf
          

